server.port=8080

spring.application.name=sistema-reservas-campestre

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/campestre_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:Kaylani24.}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect se auto-detecta
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

spring.jackson.time-zone=America/Lima
spring.jackson.locale=es_PE
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:centrorecreacionaljoseantonio@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:vyhf ttgz gvar army}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

jwt.secret=${JWT_SECRET:Cl4v3S3cr3t4C4mp3str3J0s3Ant0n10S1st3m4R3s3rv4s2026!}
jwt.expiration=86400000

whatsapp.enabled=false
whatsapp.api-url=https://graph.facebook.com/v18.0
whatsapp.phone-number-id=${WHATSAPP_PHONE_ID:}
whatsapp.access-token=${WHATSAPP_TOKEN:}

logging.level.com.campestre=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=WARN
logging.pattern.console=%d{dd/MM/yyyy HH:mm:ss} %-5level %logger{36} - %msg%n
